// Auto-generated by GitHub Actions — do not edit manually
export const firebaseConfig = {
  "apiKey": "AIzaSyC1eK0gMuO9ZG-i_HNZa-7WGgflfohj5iU",
  "authDomain": "pickflick-da4e9.firebaseapp.com",
  "databaseURL": "https://pickflick-da4e9-default-rtdb.firebaseio.com",
  "projectId": "pickflick-da4e9",
  "storageBucket": "pickflick-da4e9.firebasestorage.app",
  "messagingSenderId": "568806685855",
  "appId": "1:568806685855:web:34027b60050bfdafe076aa"
};
